### ISSUE TITLE
Name of Repo and Release Next Repo

### ISSUE THREAD

**Issue by mmsamiei** [1995parham/TanhaDarKhaneh#1]
first of all, Happy New Year!!!!! 🌸🌸🌸🌸🌸🌸🌸🌸

Isn't it better to call this repo "Home Alone" instead of "TanhaDarKhaneh"?

Another thing, Have you a plan for releasing Home Alone 2 with python theme? :)

best wishes to you!

**Comment by 1995parham** [comment]
Hi, it is fantastic to have you here. This repository is backed with a training movie that I am trying to upload on Youtube. In this repository, we will continue to see the C in action. I am happy with your opinions, and it would be great if you can contribute to this movement 😄
